import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./index.css";
import Dashboard from "@/components/dashboard/cards/Dashboard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="flex place-items-center justify-center h-screen bg-neutral-200"
    >
      <body className="flex container m-auto h-[80vh] bg-white rounded-lg">
        <Dashboard children={children} />
      </body>
    </html>
  );
}
